services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7.2.4-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-calendar-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/app/.env
    environment:
      - UVICORN_RELOAD=true
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./backend/app:/app

  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-calendar-celery-worker
    command: python celery_worker.py
    env_file:
      - ./backend/app/.env
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./backend/app:/app
    restart: always

  celery-flower:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-calendar-celery-flower
    command: celery -A celery_app flower --port=5555
    ports:
      - "5555:5555"
    env_file:
      - ./backend/app/.env
    depends_on:
      - redis
      - celery-worker
    volumes:
      - ./backend/app:/app
    restart: always

volumes:
  mongodb_data:
  redis_data:
