
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

    volumes:
      - mongodb_data:/data/db

  cache:
    image: redis:7.2.4-alpine
    restart: no

    ports:
      - '6379:6379'



  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - "8000:8000"
    env_file:
      - ./backend/app/.env
    environment:
      - UVICORN_RELOAD=true
    depends_on:
      - mongodb

volumes:
  mongodb_data: