name: Deploy AI Calendar

on:
  push:
    branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Stop existing containers
      run: |
        cd "/opt/ai-calendar"
        docker-compose down || true

    - name: Pull latest changes
      run: |
        cd "/opt/ai-calendar"
        git pull origin main

    - name: Build and start containers
      run: |
        cd "/opt/ai-calendar"
        docker-compose up -d --build

    - name: Check deployment
      run: |
        sleep 30
        docker-compose ps
        curl -f http://localhost:3000 || exit 1
