name: Deploy AI Calendar

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Stop existing containers
      run: |
        cd "/opt/ai-calendar"
        docker-compose down || true

    - name: Safe update with git stash
      run: |
        cd "/opt/ai-calendar"
        git fetch origin main
        git merge origin/main --no-edit --no-commit


    - name: Build and start containers
      run: |
        cd "/opt/ai-calendar"
        docker-compose -f docker-compose.yml --env-file .env up -d --build

    - name: Check deployment
      run: |
        cd "/opt/ai-calendar"
        sleep 30
        docker-compose ps
        curl -f http://localhost:3000 || exit 1

    - name: Cleanup unused images
      run: |
        docker image prune -f || true